[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["OrbitVisualization"]

[project]
name = "OrbitVisualization"
version = "1.0.0"

dependencies = [
 "numpy",
 "matplotlib"
]
