[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["OrbitVisualization"]
packages = ["OrbitVisualization"]

[project]
name = "OrbitVisualization"
version = "1.0.1"

dependencies = [
 "numpy",
 "matplotlib"
]
